### ISSUE TITLE
Manually-added Antlr jar not shown in preferences

### ISSUE THREAD

**Issue by kec2** [jknack/antlr4ide#128]
I have added a new Antlr4.5 complete jar through Window->Preferences->ANTLR 4->Tool.
I generating my lexer/parser, it works great.
Now going into preferences I cant see the jar that I added. This is confusing.
The tool is generating my lexer/parser with the correct Antlr version. I just cant see the jar in Preferences.

**Comment by mrostron** [comment]
hi
i am also trying to add Antlr4.5 jar thru Window->Preferences->ANTLR4->Tool, but cannot edit it, not sure why. Do you have any idea?
mr

**Comment by nttdatahenriksorensen** [comment]
Are you using Windows?
I discovered a bug when using Windows due to the way antlr4ide stores the version and jar file names. The current code use a ':' as a separator for the list entries, but the code gets confused when trying to split the list of entries at the ':', because the windows paths contains ':'.

**Comment by HSorensen** [comment]
Are you using Windows?
I discovered a bug when using Windows due to the way antlr4ide stores the version and jar file names. The current code use a ':' as a separator for the list entries, but the code gets confused when trying to split the list of entries at the ':', because the windows paths contains ':'.

**Comment by arifogel** [comment]
@HSorensen since you are now a collaborator and you have more context than me, can you pick up this issue?

**Comment by HSorensen** [comment]
This has been fixed with version 0.3.7, if not please reopen this issue.
